name: 'Slack Message'
description: 'Send slack notification in a channel'
author: 'The Cloud Connectors'
inputs:
  status:
    description: 'the build status'
    default: 'success'
  template:
    description: 'the template to use'
    default: 'build_status'
runs:
  using: node12
  main: dist/index.js